### ISSUE TITLE
Windower load screen loads blank white box on windows 10 and will not proceed further.

### ISSUE THREAD

**Issue by Irrellius** [Windower/Issues#789] opened 2015-11-04 16:20 UTC
Just got a new PC, installed FFXI, when I put windower on it says it's fine, then when I open the program it loads a white box and does nothing at all.

**Comment by alphaONE2** [comment] 2015-11-04 20:08
Duplicate of #176.

You can find a workaround in a [thread on our forums](http://forums.windower.net/index.php?/topic/588-white-screen-at-windower-launch/).

**Closed by alphaONE2** 2015-11-04 20:08 UTC
Labels: Other: Launcher, Status: Duplicate
