### ISSUE TITLE
Game crashes when switching from POL to FFXI, please help =(

### ISSUE THREAD

**Issue by shadjohn12** [Windower/Issues#858] opened 2016-12-15 04:40 UTC
#845 Game crashes when switching from POL to FFXI, please help =(
I'm new to windower 4 btw.

**Comment by kuroganashi** [comment] 2016-12-21 18:24
The problem is Display Port acts as a Plug and Play device and so does HDMI if the manufacturer decided to include it. On DP its 100% enforced on HDMI its an option for the maker, yours obviously has it...

This isn't windower bug, it effects a lot of other older games including vanilla FFXI. I'm guessing if Ashita doesn't crash they did some kind of fix or just the way they were hooking already was good to go.

A lot of people have complained to NVidia for years to have an override settings that tells it that it(monitor) that it always connected for their normal line of GFX Cards. There Quadro line of cards control panel have had this option for years. (Its really a custom config profile that you get to set.)

AMD Cards have had it for years.

The one solution for consumer grade Nvidia users is a device like this http://monitordetectkiller.com/

Here some complaints but there are many more threads about it on nvidia site: https://forums.geforce.com/default/topic/853181/hdmi-screen-hot-plug-detection-please-allow-us-to-disable-edid-/

**Comment by shadjohn12** [comment] 2016-12-21 20:31
Thank you for clarifying this to me, was so confused about what could be the problem. @kuroganashi :-)

**Comment by Byrth** [comment] 2017-04-11 13:13
Did you ever resolve this problem?

If not, would you mind testing out Windower v4.3?
* Download/extract this zip: https://www.dropbox.com/s/bx2kkkiq7rn7a6x/Windower.zip?dl=0
* Copy Windower.exe and hook.dll to your windower folder and overwrite the copies that are already there.

**Comment by Byrth** [comment] 2017-04-13 21:56
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.

**Closed by Byrth** 2017-04-13 21:56 UTC
