### ISSUE TITLE
I see only a blank white rectangle in shape of the Windower GUI when I launch it.

### ISSUE THREAD

**Issue by vinedrai** [Windower/Issues#846] opened 2016-07-08 19:32 UTC
As the title says, I can't see anything on the Windower GUI. Blindly clicking on the buttons still works, as in I can start POL from the Windower GUI by clicking on the bottom right corner where that button is normally located. When I hover the mouse cursor over the icon in the taskbar while the Windower is running, it shows the GUI normally. I tried reinstalling the windower and even system restore to a point when it used to work normally. What may be causing this weird issue?

Edit: Oddly enough, the support forums web page doesn't open for me either.

**Comment by z16** [comment] 2016-07-08 19:44
Any chance it's a duplicate of #176?

**Comment by vinedrai** [comment] 2016-07-08 21:33
seems like it, thanks for point that out but I think I can't use the workaround that involves changing the theme into a simpler one. I am already using the basic theme on windows 10. Would I break anything if I use the other workaround which involves adding some key to registry to disable hardware rendering for WPF?

**Comment by z16** [comment] 2016-07-08 21:41
I do not think so, although @alphaONE2 will know more about it. But I think it's fine, and even if it isn't, it's easily reversible.

**Comment by vinedrai** [comment] 2016-07-08 22:27
DavionCA commented on Apr 12, 2013
"That did it. I disabled hardware rendering for WPF via registry key. I had to add the key HK_Current_User\Software\Microsoft\Avalon.Graphics then add a DWORD (32-bit) entry with a value of 1."

There is already a key at that path in my registry. In that key, there is a "default" string value which is empty. Under the Avalon.Graphics key, there is another key name "DISPLAY1" which has an empty "default" string value. I tried adding a DWORD entry with a value of 1 inside the Avalon.Graphics key but that didn't fix the issue. 

I tried another workaround that was suggested in that old thread which is using a high contrast theme for Windows desktop and it worked to fix the issue, but I just can't stand using one of those eye-hurting themes.

**Comment by vinedrai** [comment] 2016-07-08 22:39
Ok. I added DWORD named "DisableHWAcceleration" inside the key "HK_Current_User\Software\Microsoft\Avalon.Graphics" with a value of 1 and it fixed the white box issue, but I hope it won't break anything. Thanks for the help.

**Comment by alphaONE2** [comment] 2016-07-08 23:32
All the DisableHWAcceleration value does is turn off hardware acceleration of WPF applications. With hardware acceleration off, they fall back to software rendering, which is what almost every other application on your desktop uses. Games, and other high-performance applications will be unaffected. So no, this shouldn't break anything. At worst you *might* notice slightly more stutter in the animations of *a few* applications.

**Closed by alphaONE2** 2016-07-08 23:32 UTC
