### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by rinkubean** [Windower/Issues#778] opened 2015-09-23 01:05 UTC
I installed Windower like any normal person would and immediately the program crashes with a "Windower Launcher has stopped working" error. I reinstalled the program multiple times and nothing changed. I recently even reinstalled Windows to which it worked for a day then randomly it stopped working again. I have no idea where to go from here so any help or ideas would be much appreciated.

On Windows 7 by the way.

**Comment by rinkubean** [comment] 2015-09-24 00:41
So I just found out what was causing it but I don't know how I'm going to exactly fix it. It turns out the problem was coming from a program I use to play another game called RadeonPro. While RadeonPro is installed, Windower crashes on launch, but if I uninstall it it works fine. I reinstall it, and Windower stops working again. What could be causing this?

**Comment by Byrth** [comment] 2015-09-24 16:34
Windower launcher should create crash.log files in its folder when it crashes. Could you copy the contents of that file to pastebin and link it?

Also, what antivirus program do you use?

**Comment by rinkubean** [comment] 2015-09-24 16:44
No crash.log file has been created on these crashes.

And I don't use an antivirus.

**Comment by Byrth** [comment] 2015-11-07 22:55
I do not know what to suggest then. There are various crash on launch problems and I am not versed in them. Perhaps alphaONE2 can help!

**Comment by alphaONE2** [comment] 2015-11-08 17:36
I think this might be a duplicate of #786. Can you try uninstalling Windows Update KB3045563?

**Comment by wildsprite** [comment] 2015-11-15 12:31
I'm having the crash on launch of FFXI from POL when using windower issue too but there is no way to uninstall dot net 4.6 in windows 10 version 1511 :/

**Comment by alphaONE2** [comment] 2015-11-15 15:04
@wildsprite: The version that comes with Windows 10 build 10240 works fine for me. Are you sure you don't have a crash log?

**Comment by timstix** [comment] 2015-11-16 03:55
Ok so read this post and it helped me narrow down my problem. My Windows 7 install does not have update KB3045563
I uninstalled KB3098781 which also removed 3037581 2972216 and now im good

**Comment by rinkubean** [comment] 2015-11-16 03:59
I don't have Windows Update KB3045563, nor do I have the update KB3098781 that the other person mentioned.

**Comment by wildsprite** [comment] 2015-11-17 08:25
I'm on windows 10 version 1511 (OS build 10586.3) <---from winver
as soon as I hit play the second time after confirm it pauses for a really long time then I get a "Playonline Viewer has stopped working"
the last thing in my crash log was from march of this year.

**Comment by wildsprite** [comment] 2015-11-17 09:55
http://www.mediafire.com/download/9u8fqwal7wdll3d/pol.dmp.7z
unfortunately due to it's size I had to compress it due to the restrictions of mediafire free accounts. I hope this is acceptable. if not I'll have to find another way to get you the file.

**Comment by wildsprite** [comment] 2015-11-20 07:17
any updates on this? 
I have a feeling this https://github.com/Windower/Issues/issues/798
is pretty much the same issue I am having

**Comment by alphaONE2** [comment] 2015-11-20 19:41
Sorry I haven't had time to look into this until now. The crash dump didn't capture any information about a crash. Everything looks like it's still running fine, or perhaps deadlocked, but not crashed. I also can't reproduce this error at all on my end.

**Comment by wildsprite** [comment] 2015-11-21 19:17
wonderful, that means I'm stuck then and can't use windower unless I can figure out another workaround :/

**Comment by wildsprite** [comment] 2015-11-22 23:30
@alphaONE2 maybe this will help? maybe not? I dunno I'm at a loss as to what even look for at this point
________________________________________________
Fault bucket 73946564794, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: pol.exe
P2: 1.18.13.0
P3: 4e3bcddc
P4: StackHash_bdcb
P5: 0.0.0.0
P6: 00000000
P7: c0000005
P8: PCH_79_FROM_ntdll+0x0007725C
P9: 
P10: 

Attached files:
C:\Users\Kita\AppData\Local\Temp\WERC8DA.tmp.WERInternalMetadata.xml

These files may be available here:

C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_pol.exe_cdbf6b6542789ec0ee2c74715926f8e2d0e8ae48_52d02681_0c84d86b

Analysis symbol: 
Rechecking for solution: 0
Report Id: b238de7c-1625-456f-9cde-38d80c70802b
Report Status: 0
Hashed bucket: a8b60daee56622c3be59d5b00ca1a099

**Comment by alphaONE2** [comment] 2015-11-23 18:36
Well, it tells us that the problem is an Access Violation (0xC0000005) and that the access violation appears to happen in ntdll.dll, but unfortunately doesn't tell us what Windower is doing to cause it, or where the offending code may be. Sorry.

**Comment by wildsprite** [comment] 2015-11-23 19:00
oh lovely, that's more than I had before but it still feels like I got a whole lot of nothing

**Comment by Decep7537** [comment] 2015-12-07 13:37
i am having the same issue. it is driving me nuts. idk if i'm posting this right but here is what crash file says:

`````````````````````````````````````````````````````````````````````
12/7/2015 8:24:48 AM
---------------------------------------------------------------------
System.TypeInitializationException: The type initializer for 'MS.Win32.Penimc.UnsafeNativeMethods' threw an exception. ---> System.Runtime.InteropServices.COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   at MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at MS.Win32.Penimc.UnsafeNativeMethods.CreatePimcManager()
   at MS.Win32.Penimc.UnsafeNativeMethods..cctor()
   --- End of inner exception stack trace ---
   at MS.Win32.Penimc.UnsafeNativeMethods.CreateResetEvent(IntPtr& handle)
   at System.Windows.Input.PenThreadWorker..ctor()
   at System.Windows.Input.PenThreadPool.GetPenThreadForPenContextHelper(PenContext penContext)
   at System.Windows.Input.PenThreadPool.GetPenThreadForPenContext(PenContext penContext)
   at System.Windows.Input.StylusLogic.GetDeviceCount()
   at System.Windows.Input.StylusLogic.get_TabletDevices()
   at System.Windows.Input.StylusLogic.RegisterHwndForInput(InputManager inputManager, PresentationSource inputSource)
   at System.Windows.Interop.HwndStylusInputProvider..ctor(HwndSource source)
   at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   at System.Windows.Interop.HwndSource..ctor(HwndSourceParameters parameters)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

sorry wouldn't let me apply the file. any help would be amazing. ty

**Comment by deviljin786** [comment] 2015-12-07 23:27
I'm getting this every time i try to launch the application 

[ 4.2.5564.39855 ] 2015-12-07 23:23:46.0373674 UTC
---------------------------------------------------------------------
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at #=qPVzKPXreBMK$G_TScC8d1Ctb_fGj44I1J70nspZgfgc=.#=q$pww7u7a8E5KBZ87oKIoig==(String #=qoOfmmNOMqhuJULvaMcWu2w==, #=qdWKs2YH5SnFgXJPCF1szgPXoHSmmSh4DrfoUED_SDBo= #=quTc0RVW0C2_5GERaxMw4LQ==, Boolean #=qhFOX1aUHv3mgiXMa34qGNQ==, TimeSpan #=qFEzHGxyOne7p37rEWbV8$w==)
   at #=qPVzKPXreBMK$G_TScC8d1Ctb_fGj44I1J70nspZgfgc=.#=qsKKl1l0g1HURDWit8B79Fw==(String #=qqKTShJx7xnazuWOpJ6ZDeg==, #=qdWKs2YH5SnFgXJPCF1szgPXoHSmmSh4DrfoUED_SDBo= #=qiV1cyIFi8uzxd23Z9RTz8A==, Boolean #=qvxtyf2yqPR87sOWe96PA4A==)
   at #=qvticlh8sdG9urHCodAc05R$Pt$DrlamfeVITJje_ohY=.#=qxA0hzrjWSVf3wZHstSp6qA==()
   at #=q4ao$U6CJ_ca3wGsQbteYRInNOUKn7px0EZirpC9v2dQ=.#=qRSqZ29WH0ZYrlsLq$sgMxA==(#=q9gJgdStyyOZoRfONVWltog== #=qhFHi0z6eBl3jv5Ev3xCTig==)
   at #=q9gJgdStyyOZoRfONVWltog==.#=q1GDlKxdSu3j9WeEYkyufMQ==()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

**Comment by alphaONE2** [comment] 2015-12-08 20:59
@Decep7537, @deviljin786: These don't look related at all.

@Decep7537: It looks like something is broken at the OS or .Net Framework level on your system. The error you're getting suggests that one of the COM dlls related to pen/stylus input is missing. Most of the information I can find seems to suggest that this may be related to Wacom devices, but I haven't found anything definitive. In any case it's probably not something we can fix on our end.

@deviljin786: This error happens when Windower can't locate a valid install of PlayOnline Viewer and/or Final Fantasy XI. If you've just installed the Steam version of Final Fantasy XI, make sure that you launch from Steam once, so that the necessary registry keys can be set up, before trying to use Windower. If you're not using the Steam version or you've already launched from Steam once and it's still occurring, try manually selecting the client region in the Windower 4 launcher.

**Comment by Byrth** [comment] 2017-04-11 13:43
Given the lack of replies in 1.5 years, I'm going to assume the problems were resolved and close this issue.

Please feel free to reopen it or start a new issue if they were not resolved.

**Closed by Byrth** 2017-04-11 13:43 UTC
Labels: Status: Not reproducible
