### ISSUE TITLE
Windower 4 will not launch Play Online Viewer after Windows 10 Pro Build 15019 update

### ISSUE THREAD

**Issue by bororidley** [Windower/Issues#867] opened 2017-01-29 22:22 UTC
I just wanted to let you all know that Microsoft pushed it's latest  "**Windows 10 Pro Insider Preview Evaluation Copy Build 15019.rs_prerelease, 170121-1513**" to my computer.
Before that I had no issues with Windower 4 working on my system.

After the update, I am having issues getting Play Online to start from Windower 4 & Windower 4 Dev. However the strange thing is Windower 3 will launch Play Online without any issues.

Basically what happens is you load up Windower 4, you click the right arrow to start Play Online, and nothing happens. Windower 4 will close and leave you at your desktop screen.

-----------------------------------------------------------------

I have tried Running POL, & Windower 4 in Admin mode, still it does not work
I have tried reinstalling Windower 4, still having the same issue.
I have check the file for Final Fantasy XI and they are fine.
I have given Read / Write Permissions for the Windower & Play Online folders
If you restore back to the previous Build of Windows 10, Windower 4 will work fine. But as soon as you go back to the new Build, Windower 4 stops working again. 

-----------------------------------------------------------------

I did fine some of the information from my Event Viewer that pertains to this issue. It loged 2 separate events in the event viewer: 1 Information log & 1 Error log this is what they say:
 
------------------------------------------------------------------------------

INFORMATION - Windows Error Reporting

"Fault bucket 108270700857, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: pol.exe
P2: 1.18.13.0
P3: 4e3bcddc
P4: Hook.dll
P5: 4.2.13.11
P6: 577df05d
P7: c0000005
P8: 0010fbf0
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2FEA.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3078.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3077.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3097.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_pol.exe_8096ab97dbd2a89da4b97f9d1a146be91c948_52d02681_2dd634ad

Analysis symbol: 
Rechecking for solution: 0
Report Id: de669950-5d68-4feb-b788-9764d19ba798
Report Status: 268435456
Hashed bucket: 045eb2bc98cc091347e1546077bc9cf7"

Event ID: 1001 
Task Category: None

------------------------------------------------------------------------------------------------

ERROR - Application Error

"Faulting application name: pol.exe, version: 1.18.13.0, time stamp: 0x4e3bcddc
Faulting module name: Hook.dll, version: 4.2.13.11, time stamp: 0x577df05d
Exception code: 0xc0000005
Fault offset: 0x0010fbf0
Faulting process id: 0x2028
Faulting application start time: 0x01d27a7ab43e1b62
Faulting application path: C:\Program Files (x86)\PlayOnline\SquareEnix\PlayOnlineViewer\pol.exe
Faulting module path: C:\Program Files (x86)\Windower4\Hook.dll
Report Id: de669950-5d68-4feb-b788-9764d19ba798
Faulting package full name: 
Faulting package-relative application ID: "

Event ID: 1000
Task Category: (100)

-------------------------------------------------------------------

I wanted to let you all know this because I see Microsoft breaking your Windower 4 with the next Windows 10 Service Pack (aka Build) update that is due out this year.

If you have any ideas on how I can fix this please let me know. In the mean time I will keep use Windower 3 on the Windows 10 Build 15019 or my back up Windows 10 partition without the Windows Build 15019.

**Comment by nyankochan** [comment] 2017-02-07 00:12
Build 15019(x86_64) : orignal 'Play Online' Crash. Windows10 W32 problem.(64bit and 32bit)
Build 15025(x86_64) : orignal 'Play Online' OK. but Hook.dll Crash.
maybe updating of Hook.dll.
waiting 'Creators Update' pre-release version.

**Comment by Niverive** [comment] 2017-02-08 04:44
I would like to comment that it also doesn't work on 15025.

**Comment by bororidley** [comment] 2017-03-04 22:15
I am now up to WIndows 10 Pro Insider Preview Build 15048 and Windower 4 is still will not working.

**Comment by Byrth** [comment] 2017-03-06 14:09
We talked about this problem today on IRC. Summary is:
1) Iryoku (our launcher guru) doesn't have a box to install this prerelease windows on, so he can't debug it
2) However, we have a second launcher (for v5) that might work.

So the plan is to give you a version of v5 and see whether it fixes your problem. If it does, we'll backport the relevant parts to v4. We're only borderline comfortable with having such a proto-version out in the wild, so please let me know when you've picked it up so I can delete the zip from my dropbox.
https://www.dropbox.com/s/e9dsqp7bjdrslv1/v5.zip?dl=0

**Comment by Byrth** [comment] 2017-03-06 14:55
One moment, actually. We need to get a different version to compile so you can actually use it on your computer.

**Comment by Byrth** [comment] 2017-03-06 15:18
Okay, different build:
https://www.dropbox.com/s/c9viyacermhfix8/v5.zip?dl=0

**Comment by bororidley** [comment] 2017-03-07 00:34
I did try the new Windower, and it Worked :) Play Online Launched, now I just need the Add-on's & Plugin's. LOL 

You can actually sign up for the free for the Windows 10 Pro Insider Preview Evaluation copies in Windows 10. Just go to Settings > Windows Insider Program > Get Started. Then under "What Pace do you want to get builds" I chose FAST. 

Just keep in mind Microsoft will push these updates to your computer, without you knowing about it. So be sure to have a spare computer for testing the Windower against these new builds. 
I just wish I knew what Microsoft did to break Windower 4 in the first place.

**Comment by bororidley** [comment] 2017-03-07 00:45
I have been noticing one weird issue this entire time. Anytime I go to launch the Windower 4, it defaults back all my Final Fantasy XI Settings. Which forces me to reset all my setting in the Final Fantasy XI Config in order to get the game to launch properly. It is like Windower was over riding and wiping out my FFXI Settings. 
I just thought I would let you know this as well. 
If you want to reach out to me please email me your contact info either phone number or Skype name to ktf1179@hotmail.com so we can set up a time to talk if you want.

**Comment by alphaONE2** [comment] 2017-03-07 02:21
(just to clarify, I'm the "launcher guru" @Byrth mentioned)

So, Windower 5 is not anywhere near finished; the addon API isn't fully implemented, and there are no addons available for it yet. Thankfully it launches, so if we can isolate the problem in Windwoer 4, we may be able to back port part of Windower 5 to fix the issue.

Next we'll need to determine if the issue is in the launcher or if it's in hook. Is it possible for you to get on IRC (the #windower or #lua channels on the ffochat.com network)?

P.S. I'm well aware of how to get the Insider builds. I just don't have a spare PC I can install them on right now.

**Comment by JordanKidd** [comment] 2017-03-29 19:06
Today, after changing nothing and using v4 for months, I received this same issue. Also using Windows 10 here. I checked my updates and I see nothing from Windows within the last couple of days. Without Windower still launches the game fine. The linked v5 allows me passed the handoff between POL and FFXI, unlike the v4 and v4 dev build on the homepage. My errors are also the same listed above within Event Viewer.

**Comment by 6969696969696969** [comment] 2017-03-30 23:33
This is also true with the RTM build for the Creator's Update for Windows 10 (Build 15063).  I was playing FFXI the other morning and all was working well, including Windower 4.  I had read an article that Microsoft had released the ISO files for Windows 10, build 15063.  I downloaded the ISO, and upgraded my OS.  When I tried to play FFXI in Windower 4 the initial update splash screen appeared and then it just crashed.  I tried several times to get it to work, but the furthest I managed to get was to get the login screen to appear...it was frozen and when I clicked on it it crashed.

**Comment by yetanotherguy** [comment] 2017-04-07 16:52
Running Creator update and having the exact same issues.  Included two crash dumps.  Smaller one is when it fails silently, larger one is when POL looks like its starting up and dies on the login / account selection screen.
[dumps.zip](https://github.com/Windower/Issues/files/906214/dumps.zip)

**Comment by mooglesoft** [comment] 2017-04-09 20:27
Having the same issue as everyone else---Windower never actually launches POL (yet it runs just fine outside of Windower if I launch it from Steam).  Creator's Update goes live in a few days so I imagine several people are going to have this problem.  Any chance we can get a copy of the v5 fix until the patched version of Windower comes out?  Thank you!

**Comment by alphaONE2** [comment] 2017-04-09 20:33
You wouldn't be able to do anything with v5 that you couldn't do with the vanilla game; it doesn't even have any addons (and no, you can't just copy addons from v4, the API is completely different).

I'm working hard to get v4 working on build 15063, before it goes live on the 11th.

**Comment by mooglesoft** [comment] 2017-04-09 20:34
Gotcha.  Guess I'm waiting or rolling back then.  Thanks for the quick
response and for all of your effort keeping Windower working for all of us!

**Comment by joshk6656** [comment] 2017-04-11 06:39
@alphaONE2 finished tonight. its not pushed yet, but you can try it here (it may be pushed to dev soon)

https://www.dropbox.com/s/om1t9msjp97p69p/Windower%204.3.zip?dl=0

**Comment by 6969696969696969** [comment] 2017-04-11 07:13
I just downloaded it and put the files in my Windower 4 directory (renamed the original dll & exe, put the new files there).  It seems to work…I am standing in my Mog Garden, in Windower 4.3…on Windows 10, Build 15063.  My add-ons & plugins all seemed to load with no issues.  Thanks for fixing this.

**Comment by Byrth** [comment] 2017-04-11 07:24
I haven't installed the Creators Update yet, but using //list crashes me if I use it while logged in with the linked Launcher/hook combo.

**Comment by 6969696969696969** [comment] 2017-04-11 07:27
> but using //list crashes me if I use it while logged in with the linked Launcher/hook combo.<

it does this on 15063 (Creators Update) as well.

**Comment by Byrth** [comment] 2017-04-11 12:28
Did some more testing without the Creator's Update. First, the good:
* No memory leak issues detected.
* I exhaustively tested them per our documentation, and vast majority of commands still work.

Second, two things that are also broken in v4.2:
* keyboard_type / type does add things to the chat input bar but it strips off windower commands (like input) and the first quotation mark.
* setting game_gamma to 1 briefly reduced my entire screen's brightness and then caused it to flicker back to normal. I couldn't get any repeatable effect using this command.

Third, things that are broken in v4.3:
* ```//list``` or ```//plugin_list``` normally displays a list of current plugins in the chat log. In v4.3, it causes a crash 100% of the time if used when logged in.
* ```//lua list```, which displays the addons running in LuaCore, also causes a crash.
* We previously had an issue where Windower would revert alt-tab's preview to classic mode. Now there's no preview and it also won't let you alt-tab even from other windows

This is all I've found. Good job!

**Comment by Byrth** [comment] 2017-04-11 12:32
After not consciously changing anything, now Alt-Tab Classic works again.

**Comment by Byrth** [comment] 2017-04-11 14:25
It would be great if we could get #866 and #851 killed in this same hook update.

**Comment by skrimpy** [comment] 2017-04-11 19:25
Just wanted to note that the Windower build in dropbox worked for me on Build 15063.14 - Thanks guys :)  About to play a bit and see if all works, but POL is launching and loading ffxi now.

**Comment by dpn982** [comment] 2017-04-12 01:45
I tried the uploaded updated version and it is crashing for me.  Here is the crash log:
[crash.txt](https://github.com/Windower/Issues/files/915164/crash.txt)

**Comment by alphaONE2** [comment] 2017-04-12 01:47
@dpn982, could you please try it with the 4.2 launcher?

**Comment by 6969696969696969** [comment] 2017-04-12 03:01
Alt-Tab does not work for me.  If it does, its sporadic and it only works once (can alt-tab to browser, but cannot alt-tab back to the game).

**Comment by alphaONE2** [comment] 2017-04-12 03:02
We're aware of the alt-tab issue, but not sure what changed to cause it.

**Comment by Daleterrence** [comment] 2017-04-12 04:22
I just updated to 10.0.15063.13 Version 1703 and I'm having the following issues which are probably related to this;

4.2.5566.34367 - Nothing, POL doesn't launch. 
37379 - Same issue, POL just doesn't launch. 

4.3.6310.39414 - Crashes at "Launching PlayOnline".
39423 - Same issue. 

Both crashes seem to be the same thing but I've included both in the file below. 
[crash.txt](https://github.com/Windower/Issues/files/915380/crash.txt)

Probably going to go back to the previous build until it's fixed, just thought I'd share.

**Comment by valient85** [comment] 2017-04-13 02:11
Using the 4.3 hook and launcher is causing my game to crash when using <st> command to sub target.

**Comment by Byrth** [comment] 2017-04-13 21:54
The <st > issue should be fixed in the most recent version.

v4.3 and the new Launcher are both currently on -dev. If you are having problems with the Creators Update and want to log back in, we recommend at least temporarily using -dev. To do this, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in.

**Closed by Byrth** 2017-04-13 21:54 UTC
