### ISSUE TITLE
Windower Launcher has stopped working... on first launch.

### ISSUE THREAD

**Issue by HSylux** [Windower/Issues#875] opened 2017-04-07 11:46 UTC
Program doesn't do anything. It just gets to "LuaCore: Extracting Files [ 0 / 0 ]" then it crashes. Nothing more than that.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Windower.exe
  Problem Signature 02:	4.0.4881.17534
  Problem Signature 03:	5190fc55
  Problem Signature 04:	Ionic.Zip
  Problem Signature 05:	1.9.1.8
  Problem Signature 06:	4e3df203
  Problem Signature 07:	119
  Problem Signature 08:	31
  Problem Signature 09:	Ionic.Zip.ZipException

> Ionic.Zip.ZipException:
 Could not read C:\Program Files (x86)\Windower4\updates\temp\39aa5189-dd18-490d-8afe-102ffe6d1421 as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException: Could not read block - no data!  (position 0x00000000)
   at Ionic.Zip.SharedUtilities._ReadFourBytes(Stream s, String message)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at #=qLpkVB1CGzRPMrP$f9QWGqpJaIjQGe8BVG0zG9nlfpC0dr9l6BO0MlNAECVllWMUS.#=qbVcvel8s_GfYNuaNLT6Y8A==(#=qx24zpJDwDB2K$ccvulMnUAtqZtLL2_POy9O_ieP3rM0= #=qesQ7VZod4bj9I4wbI5_pfQ==, String #=qxVLWGx1RefFvW4Wowk$fXw==, String #=qPu0eYZ1UrZrw4Zy6fzmIzw==, String #=q0t38DsbfsX$B9JU8sFf7cQ==)
   at #=qLpkVB1CGzRPMrP$f9QWGqpJaIjQGe8BVG0zG9nlfpC0dr9l6BO0MlNAECVllWMUS.#=q9hPyUWnAfbgTxvae8HX$7Q==()
   at #=qwrZ0sKWfVuSrbsrEe$sq2ikYRakTupw24tqRYOrFtO4=.#=qnQCMKMqRLmsGND5_yA3M5Q==()
   at #=qAlk$Mw_tywKjs9rd7cyoVByKGVe3vaaXeS_LGtl1hBE=.#=qfyJ2oWactrEI0jMMW5DrEA==(#=qmhNvAyztrFon0QQMItVoEw== #=q$_uA1omHXJgXxHzgfPGREA==)
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qav9FVComJWu2k_c7i_yB0A==()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Byrth** [comment] 2017-04-07 12:11
Please try to run the launcher again. I'm closing this because it's a duplicate of #874 , so please reply over there.

**Closed by Byrth** 2017-04-07 12:11 UTC
