### ISSUE TITLE
windower getting stuck at loading playonline

### ISSUE THREAD

**Issue by zaxtiss** [Windower/Issues#899] opened 2017-05-01 23:34 UTC
ok so windower just updated the hook to 4.3.0.6 and its getting stuck at the loading playonline screen.
i tried restarting my PC.
i'm running it as admin.
so i don't know what is wrong :(

**Comment by Stratusx** [comment] 2017-05-02 02:40
currently certain PCs are having problems with loading playonline via windower, however playonline's original (Without windower) still works, if you already windower installed prior to the new hook being updated, go to system restore, Start->all programs->accessories->system tools->->system restore
Restore your computer to a previous date that had the previous hook, then after your computer restarts/unplug/disable/turn off your internet,load windower and the auto update won't activate because theres no internet. load as many screens that you need to run your charactors until you reach the playonline sign in screen. then reconnect your internet and you'll be good.

This methord is a temp fix as suggested by byrth so please be patient until the problem is found and updated

Also, please post any dump reports on this site in regards to this problem that may have logged.
Currently there are very few reports coming in and the team has mentioned it makes it harder to narrow down the problem without those reports, include also information including system infomation "Start button -> all programs, accessories, system tools, system information". click the edit button to select all then click the edit button again then select copy, if you are using windows 10, include if your using the creators edition 
also include what plugins, add-ons are on if you have the time incase those have any connection to the problem

**Comment by zaxtiss** [comment] 2017-05-02 16:27
im using windows 7 pro SP1 iirc
i havent gotten any crashes it just gets stuck at the "Loading Playonline" after choosing a profile and hitting start.

**Comment by cairface** [comment] 2017-05-03 22:28
We've pushed an update to the development branch where this should be addressed.

Please give it a try: http://update.windower.net/dev/Windower.exe

**Comment by pxk01501** [comment] 2017-05-04 00:38
Cairface, I tried it.  POL comes out. GJ!
My condition is Win7 32bit.
But returning from minimize is not good, it cause crash.(this is another problem).

**Comment by KenshiDRK** [comment] 2017-05-04 00:43
Are you using live or dev? Dev as a new hook (4.3.0.7), I don't crash when minimize with dev version.

**Comment by pxk01501** [comment] 2017-05-04 01:17
No, My Hook.dll is 4.3.6.
4.3.0.7 goes well?

**Comment by pxk01501** [comment] 2017-05-04 01:17
sorry 4.3.6->4.3.0.6.

**Comment by KenshiDRK** [comment] 2017-05-04 01:20
Im using the 4.3.0.7 and minimize works well

**Comment by pxk01501** [comment] 2017-05-04 06:24
Where can I get Hook 4.3.0.7 ?

**Comment by pxk01501** [comment] 2017-05-04 07:08
I got from http://update.windower.net/dev/Hook.dll.

**Comment by cairface** [comment] 2017-05-04 11:56
I'm closing this issue as per feedback.

**Closed by cairface** 2017-05-04 11:56 UTC
