### ISSUE TITLE
Windower 4 launch issue

### ISSUE THREAD

**Issue by Penfoldius** [Windower/Issues#880] opened 2017-04-20 11:42 UTC
I reecently updated Windows 10 to Version 1703 and OS build 15063.138. whenever I go to launch  FFXI through Windower, Windower 4 window just disappears and nothing happens. I have tried to disable Game Mode as well and the prolem still persists. Are there any known issues in regard to this new update for Windows?

**Comment by alphaONE2** [comment] 2017-04-20 22:34
Most likely a duplicate of #867. Try the [4.3 development build](http://update.windower.net/dev/Windower.exe).

**Closed** 2017-04-20 22:34 UTC
Labels: Status: Duplicate
