### ISSUE TITLE
IPC not communicating bug is back

### ISSUE THREAD

**Issue by amadeus1171** [Windower/Issues#978] opened 2018-02-05 22:45 UTC
Remember, Archon?  When one instance crashes after being up for some time, will not communicate with other instances using IPC.  This also sometimes happens when initially logging on instances.

Can you add a lua property to show which IPC port the instance is using?  I try to take not of it when I log on, but i goes back too fast.

**Comment by cairthenn** [comment] 2018-05-23 03:11
Closed #962, #613, #941  as a duplicate of this

**Closed** 2018-07-24 11:43 UTC
Labels: Status: Implemented, Status: Pending
