### ISSUE TITLE
Windower not hooking into POL after update to Windows on 04/23/2017

### ISSUE THREAD

**Issue by Gigantormd** [Windower/Issues#882] opened 2017-04-23 15:31 UTC
The supported version of Windower 4 is not working this morning.  Microsoft pushed a rather large update to my machine last night that had my system updating for ~45 min this am.  Windower will do its update check, then display launching PlayOnline - then just shut down.  Downloaded the development version of Windower, and that launched no problem.

**Comment by Byrth** [comment] 2017-04-23 15:40
This is a duplicate of #877 

Use this version of the Launcher: http://update.windower.net/dev/Windower.exe

**Closed by Byrth** 2017-04-23 15:40 UTC
