### ISSUE TITLE
Cancel addon not working

### ISSUE THREAD

**Issue by Kaaji1359** [Windower/Issues#787] opened 2015-10-25 21:25 UTC
The "Cancel" addon appears to only be working sometimes - this just started happening, I believe, since the most recent update (I noticed it on 10/25/2015 and on 10/23/2015 it was working fine). 

It'll work for 1 buff, but then break and not work for other buffs... As an example: I load the addon, get Copy Image (4+), use //cancel Copy Image (4+), and Copy Image (4+) is canceled. I then get Copy Image (3), and //cancel Copy Image (3) fails to work (I tried //cancel Sneak and other buffs as well, but no luck), but it will still work on Copy Image (4+).

**Comment by Byrth** [comment] 2015-10-25 21:54
I can't replicate this issue. Are you testing it in Salvage?

**Comment by Kaaji1359** [comment] 2015-10-25 22:09
Sorry I'm unfamiliar with Salvage. No specific zone or anything... It still appears broken to me. //cancel doesn't work, /console cancel doesn't work, specifying the ID doesn't work or the name...

**Comment by Kaaji1359** [comment] 2015-10-25 22:34
Hi Byrth,

Is there anything I can do to help you debug this? It's very repeatable on my machine. Thank you for looking into this.

**Comment by Byrth** [comment] 2015-10-25 23:44
Load the eval addon and do this while you're having the problem:
```eval for i,v in pairs(windower.ffxi.get_player().buffs) do windower.add_to_chat(8,tostring(i)..' '..tostring(v)) end```

Then tell me what it prints out

**Comment by Kaaji1359** [comment] 2015-10-26 05:17
It appears that the list of active buffs I have is not being updated correctly. The first time I did it, I had Sanction, Exp buff, and Copy Image (4+) up. This is what it printed out:

1 445; 2 249; 3 256; 4 0... all the way to 19 0...

//cancel 249 and //cancel 256 worked to cancel Sanction and EXP buff, but Copy Image (4+) is 446, not 445, which is exactly what was failing to cancel out. 

I re-applied Signet, Exp buff, and Copy Image (4+) and re-did that command and this is what printed out a second time:

1 445, 2 0... all the way to 17 0...

It didn't even see that I had Signet or my EXP Buff this time - it's like it wasn't reading my buffs correctly and thought I only had Copy Image (3) up, even though I had Copy Image (4+) up which is 446 not 445. //cancel wouldn't work on anything this time. 

This action continues until I zone. Once I zoned, my active buff list updated, but it still wouldn't read NEW buffs that were put on me. Zoning appears to be the only temporary fix for this, and even then the active buff list still hangs and gets caught up on old buffs that aren't there anymore.

**Comment by Byrth** [comment] 2015-10-27 18:16
I think that you might have an old version of LuaCore somehow. Try this and see if it fixes it:
https://www.dropbox.com/s/la5jz88ftj1bpkd/LuaCore.dll?dl=0

**Comment by Kaaji1359** [comment] 2015-10-27 19:20
Same problem. I replaced LuaCore.dll in the Windower4 file and moved the old one out. Same thing is happening... I logged in and it wouldn't register any new buffs that were applied at all - it ONLY updates the currently buffed list when I zone or log on for the first time, that's it. 

Any other suggestions? I really enjoy this plugin :(

**Comment by Byrth** [comment] 2015-10-28 11:32
Just to be clear, you're using the cancel addon, right? The plugin was deprecated a long time ago.

If you're using the addon, what you're describing sounds like a problem in either hook or LuaCore. Could you please tell me your hook version? (windower folder -> right click hook.dll -> Properties -> Details tab -> File Version)

**Comment by Kaaji1359** [comment] 2015-10-30 04:03
Hi Byrth, sorry about the delay - I was traveling for work. 

I am using the "Cancel" addon: "Mimics the cancel plugin, but also accepts buff names instead of just IDs" as described in Windower. I don't see a Cancel plugin, just the addon. When you say deprecated, do you mean stopped working on due to disapproval? Is there a different addon that's replaced Cancel? I've definitely grown accustomed to it and just trying to figure out why it suddenly stopped working. 

Hook.dll version is 4.2.13.6.

**Comment by z16** [comment] 2015-10-30 05:36
No, what he means is that there used to be a plugin, which has since been deprecated (i.e. we cut support for it) and has later been removed entirely. Many of our addons used to be plugins at some point. [This file](https://gist.github.com/z16/f73d0912e5c5ed02c58b) documents the changes. If you were using the plugin still it wouldn't be surprising that it isn't working, hence @Byrth asked that question.

**Comment by Kaaji1359** [comment] 2015-10-30 06:54
I see, makes sense - thank you for the clarification. I'm definitely using the Cancel addon and not the plugin. 

Is that hook.dll correct?

**Comment by z16** [comment] 2015-10-30 13:25
Yes, that is the most recent version. You can check that out [here](https://github.com/Windower/Issues/blob/master/ChangeLog.md), we always update this file when either hook or one of the plugins gets updated.

This may not be very comforting, but you're not the only one experiencing issues regarding buffs. There seems to be a problem rooted in our hook somewhere, but we could not identify it yet, mostly because the issue does not seem to happen for everyone. I will be looking into it further this weekend, I could not get to it because my PC died and between work and other things it took a while to get completely set up again.

**Comment by Kaaji1359** [comment] 2015-10-30 16:13
Hi z16, thanks for the update. It's comforting knowing that people are looking into it. If you need me to do anything let me know, or if you find an update. Thanks!

**Comment by Kaaji1359** [comment] 2015-11-15 02:30
Any update on this? BTW, I'm not sure if it was ever mentioned, but I'm playing on the SuperNova private server - not sure if that changes anything.

**Comment by z16** [comment] 2015-11-15 07:18
That could be part of the issue, but I'm not sure. Try cancelling buffs manually, does that work for you, or does it experience the same symptoms?

**Comment by Kaaji1359** [comment] 2015-11-16 02:41
Cancelling buffs manually does work.

**Comment by Byrth** [comment] 2015-11-30 20:06
It appears that DarkStar based private servers handle buff packets differently than retail servers, so this is likely not an issue caused by the Cancel addon.

**Comment by Kaaji1359** [comment] 2015-12-01 06:07
Hmm, I'm assuming the SuperNova server is similar then. Maybe I can talk to one of the developers about it then...

**Comment by Byrth** [comment] 2015-12-01 16:49
kjLotus apparently fixed this issue last night, maybe? If they use the current DSP, I think it should work.

**Comment by Kaaji1359** [comment] 2015-12-02 04:30
Byrth, I'm on the SuperNova server so it's probably slightly different - it still doesn't work. With that said, now that I know that it's probably a private server related issue and not an addon issue, I'll try and talk to some developers and see if I can get an answer out of them. This makes a lot of sense, as this problem originally started during an update.

**Comment by Byrth** [comment] 2016-12-21 13:43
Okay, going to close this issue as it's a private server issue.

**Closed by Byrth** 2016-12-21 13:43 UTC
