### ISSUE TITLE
windower4 crashing without error when ever i click on quest

### ISSUE THREAD

**Issue by minfila** [Windower/Issues#1101] opened 2024-05-14 04:39 UTC
when ever i launch game and click on quest the game will close with no errors this is what I'm getting in crash log any help would be greatly appreciated

System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by RubenatorX** [comment] 2024-05-14 04:50
1) the crash log only logs errors when launching the game, not when crashing during gameplay, so that error must necesarilly be unrelated.
2) a game crash that happens when opening that menu is caused by using outdated game DAT modifications, specifically `ROM\119\51.DAT`
As this is not a Windower issue, I am closing the issue. If you have further questions, please ask in #ffxi-support on the discord server. Thanks.

**Closed as completed by RubenatorX** 2024-05-14 04:50 UTC
