### ISSUE TITLE
Windows 10 FCU

### ISSUE THREAD

**Issue by 6969696969696969** [Windower/Issues#949] opened 2017-10-03 21:13 UTC
I just got done installing the RTM build of the Windows 10 FCU update (16299.15 (x64) - update will be released to the public on Oct. 17).  I tried to use Windower (Dev) 4.3.6349.31918/hook 4.3.2.1 but it does not work.  The splash screen is displayed and then it goes away and that's it (nothing else happens, no error message, nothing).  I have tried on both the regular & dev versions and neither works.

I found this in the event viewer
Faulting application name: pol.exe, version: 1.18.13.0, time stamp: 0x4e3bcddc
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x2cd1ce3d
Exception code: 0xc06d007e
Fault offset: 0x001008b2
Faulting process id: 0x3428
Faulting application start time: 0x01d33c8a29470787
Faulting application path: G:\GAMES\PlayOnline\SquareEnix\PlayOnlineViewer\pol.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6a9fe314-b289-4503-9de2-72014062b58e
Faulting package full name: 
Faulting package-relative application ID: 
[pol.exe.8864.zip](https://github.com/Windower/Issues/files/1354030/pol.exe.8864.zip)

I can say that POL/FFXI works...and that other program that starts with an A also works. Windower however does not work.  I even tried doing a reset of my system in case something went wrong with the upgrade and Windower still does not work.
_______________________________________________________________________________________________________________
I was looking through the issues and see this is the same as https://github.com/Windower/Issues/issues/942  If you want to move or merge this with that, that would be fine.

**Comment by z16** [comment] 2017-10-21 09:47
Duplicate of #942.

**Closed by z16** 2017-10-21 09:47 UTC
