### ISSUE TITLE
Add Support for F13-F24

### ISSUE THREAD

**Issue by Chiaia** [Windower/Issues#864] opened 2017-01-17 13:13 UTC
Was wondering if support for binding F13-F24 could be added? It would make it easier to use other extended keyboards that are not supported by the binder plugin this way.

**Comment by joshk6656** [comment] 2017-01-17 20:40
The best way to do this is to work with @framerate, this is from the windower forums

"The best way to get a device added to Binder is to ask me on IRC in the #windower channel on ffochat.com. The process involves answering a lot of questions, running some tools, sending back the results and testing builds as I figure out how the device works. I also need to be clear that I can't guarantee anything, some devices simply cannot be interfaced with directly from user mode, and require a kernel mode filter driver. If this is the case with your device, then there's nothing I can do."

**Comment by Chiaia** [comment] 2017-01-17 23:45
Well thank you for the info but that wouldn't help me in my case and I knew that before posting this. I posted this because if F13-F24 support was added that would give 60 extra binds "!^#@" so that almost any keyboard could be used even if they couldn't add support via binder plugin.

**Comment by Byrth** [comment] 2017-01-24 15:41
I think even if we add your keyboard to Binder it's not going to let you use those key names as shortcuts. Like, I don't think you can alias !keyboard_f13 to something, but I might be wrong.

**Comment by z16** [comment] 2017-01-24 15:47
We discussed this on IRC briefly, the problem is that there seem to be only DIK codes for F13-15 and no further. And we're not even sure if those keys would correspond to the keys you want, as they were originally intended for a certain japanese keyboard layout. Any chance you can find out if there are any specific DIK codes it uses? There should be tools to figure this out.

**Comment by alphaONE2** [comment] 2017-01-24 16:17
The crux of the problem is that DirectInput uses keyboard scan codes directly, and doesn't do any kind of translation to normalize different keyboard layouts. F1 through F12 have standardized scan codes that are the same across most, if not all, keyboards, but there are no scan codes for F13-F24 in the US 101/102 key layouts, or European keyboard layouts. As @z16 said, there is one very old Japanese keyboard layout that had physical F13, F14 and F15 keys, and these do indeed have scan codes that DirectInput can see, but it's not clear that you can even generate them correctly unless you have Windows set to the Japanese NEC PC-98 keyboard layout.

Windows has support for F13-F24 in its Virtual Key Code mapping, but this mapping happens at a higher level, after DirectInput has processed the key. These key codes are just special case mappings of Shift+F1 through Shift+F12.

**Comment by Byrth** [comment] 2017-04-11 13:18
Consensus seems to be that we won't be adding this, so I'm going to close the request.

**Closed by Byrth** 2017-04-11 13:18 UTC
Labels: Other: Hook, Status: Won't Fix, Type: Feature Request
