### ISSUE TITLE
Lag when switching to/from FFXI instances

### ISSUE THREAD

**Issue by MartelRagnarok** [Windower/Issues#956] opened 2017-10-26 02:21 UTC
I'm experiencing significant lag whenever I change focus to or from an instance of FFXI. The game locks up for 1~ second, then skips to catch up. Even happens when Alt+Tabbing. For normal single-instance play, no big deal. But for dualboxing this is really irritating.

About all I've been able to determine about the cause is that it's something central to windower. The issue doesn't occur in vanilla POL. And I downloaded a fresh windower4 install and logged in with no addons/plugins and still had the lag. So it's not addon/plugin related.

Not really sure what else to try now. Please let me know if any additional info is needed. I'll do whatever I can to help resolve this.

**Comment by cairface** [comment] 2017-10-26 03:39
Duplicate of #955

**Closed by cairface** 2017-10-26 03:39 UTC

**Comment by z16** [comment] 2017-10-26 05:44
And just so you know, cair has been working on this particular issue all day, we know the error, but fixing it turns out to be a bit more complex than expected (as it's connected to other volatile features), so no timeline on that yet.

**Comment by MartelRagnarok** [comment] 2017-10-26 12:16
I'm just glad to hear it's being worked on. Thanks.
