### ISSUE TITLE
Windower.exe corrupted?

### ISSUE THREAD

**Issue by celoria** [Windower/Issues#716] opened 2015-04-08 23:49 UTC
Crashing as soon as I try to go from profile selection to PoL to log in

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Windower.exe
  Problem Signature 02:	4.2.5564.39855
  Problem Signature 03:	5515c6d8
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.34209
  Problem Signature 06:	534894cc
  Problem Signature 07:	4527
  Problem Signature 08:	1f4
  Problem Signature 09:	System.IO.IOException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by celoria** [comment] 2015-04-08 23:57
Had to uninstall and reinstall to get it working

**Comment by z16** [comment] 2015-04-09 00:05
Are you able to reproduce it somehow? If not we will have to close it because that info does not help us. Unless it isn't a POL crash but a Windower crash instead. If so, you should find a `crash.log` file in your Windower folder. Could you show is the content of that file, if this is the case?

**Comment by celoria** [comment] 2015-04-09 00:10
I can't reproduce now that I uninstalled and reinstalled, however I didn't delete any of my files from the windower file. I "believe" this is the crash.

[ 4.2.5564.39855 ] 2015-04-08 23:45:32.1748910 UTC
---------------------------------------------------------------------
System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Windower4\scripts\autoload\autoload.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode)
   at #=qPVzKPXreBMK$G_TScC8d1Ctb_fGj44I1J70nspZgfgc=.#=q$pww7u7a8E5KBZ87oKIoig==(String #=qoOfmmNOMqhuJULvaMcWu2w==, #=qdWKs2YH5SnFgXJPCF1szgPXoHSmmSh4DrfoUED_SDBo= #=quTc0RVW0C2_5GERaxMw4LQ==, Boolean #=qhFOX1aUHv3mgiXMa34qGNQ==, TimeSpan #=qFEzHGxyOne7p37rEWbV8$w==)
   at #=qPVzKPXreBMK$G_TScC8d1Ctb_fGj44I1J70nspZgfgc=.#=qsKKl1l0g1HURDWit8B79Fw==(String #=qqKTShJx7xnazuWOpJ6ZDeg==, #=qdWKs2YH5SnFgXJPCF1szgPXoHSmmSh4DrfoUED_SDBo= #=qiV1cyIFi8uzxd23Z9RTz8A==, Boolean #=qvxtyf2yqPR87sOWe96PA4A==)
   at #=qvticlh8sdG9urHCodAc05R$Pt$DrlamfeVITJje_ohY=.#=qxA0hzrjWSVf3wZHstSp6qA==()
   at #=q4ao$U6CJ_ca3wGsQbteYRInNOUKn7px0EZirpC9v2dQ=.#=qRSqZ29WH0ZYrlsLq$sgMxA==(#=q9gJgdStyyOZoRfONVWltog== #=qhFHi0z6eBl3jv5Ev3xCTig==)
   at #=q9gJgdStyyOZoRfONVWltog==.#=q1GDlKxdSu3j9WeEYkyufMQ==()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Byrth** [comment] 2015-08-08 16:24
I'm going to arbitrarily blame this on an antivirus program. Until we get more data (which we can't, because the OP found a solution), we can't solve it anyway, so I'm going to close it.

**Closed by Byrth** 2015-08-08 16:24 UTC
