### ISSUE TITLE
POL Hook issues. 4-28-2017

### ISSUE THREAD

**Issue by kuroganashi** [Windower/Issues#885] opened 2017-04-28 19:15 UTC
Today Windower has done an update from Hook 4.3.0.5 to Hook 4.3.0.6 and Game Crashes are happening left and right within 1 minute of logging on a character.

This is attributed towards the Hook update done on 4-28-2017
Therefore , would be in dire need of an update to 4.3.0.7 or downgrade to 4.3.0.5 til further testing.

**Comment by z16** [comment] 2017-04-28 19:44
Please do us a favor and provide us with a [crash dump](https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps). Just saying it's crashing doesn't help us. At the very least try to provide us at least with some more information about how/when it's crashing, otherwise we can't do anything. It's obviously not crashing for us or we wouldn't have pushed the update, so it's not something we can fix on our own, because we don't have anything to fix for us.

**Comment by joshk6656** [comment] 2017-04-28 20:07
I'd also recommend checking your init.txt file to see if its loading any plugins. If it is, remove them and load all your plugins through launcher.

**Comment by wxm197745** [comment] 2017-04-29 02:40
I also encountered the same problem with you, how can we solve now?

**Comment by novio** [comment] 2017-04-29 03:05
I've also encountered this same issue. 

I unloaded all my addons/plugins, which isn't very many, to eliminate the cause. It came down to two for me: autoexec and wincontrol. The first of which I have do various tasks on login per my two chars, cm p, ll profiles, etc. Wincontrol self explanitory.

I set up crash dump but it's not creating any mini dumps as it normally would for some odd reason, else I'd supply them.

**Comment by joshk6656** [comment] 2017-04-29 03:33
@novio could you try this dumpsetup instead to see if it makes dumps? if so, please post them so we can have a look.

@wxm197745 please stop spamming issues. thanks.

https://drive.google.com/file/d/0B1-GYvFFRpK6bTNNMnIwb2hYSDA/view?usp=sharing

**Comment by novio** [comment] 2017-04-29 18:29
@joshk6656 

Aye I've been using that. The issue sadly is that the windower client actually freezes and doesn't crash, you're forced to end task the process. Any time a command is sent with wincontrol ie (wincontrol move 50 50) the client then locks up. No dump is created. Lastly should I open this in a different post? I feel as if I'm stealing this one lol

**Comment by joshk6656** [comment] 2017-04-29 18:50
We are aware of WinControl causing deadlocks.

**Comment by z16** [comment] 2017-04-30 19:20
@novio That sounds like a different issue than what @kuroganashi describes. I would open another issue for that.

@kuroganashi Sorry this got a bit derailed, but we'd still like to ask for a crash dump. Did you get the chance to make one yet?

**Comment by cairface** [comment] 2017-07-13 07:15
I'm going go close this because it did not actually reference a specific solvable problem, and nearly every crash during this time frame was addressed.

**Closed by cairface** 2017-07-13 07:15 UTC
Labels: Request: Crash dump, Status: Invalid, Windower 4.3
