### ISSUE TITLE
ALT Keybinds Not Working

### ISSUE THREAD

**Issue by Kinkles** [Windower/Issues#900] opened 2017-05-02 06:25 UTC
Haven't seen anyone post any problems with ALT binds not working but mine are not anymore. I know about the Windows key issue.  I don't believe it the same as the other person that posted abotu ALT binds I think his/her were default in game ones.

**Comment by Stratusx** [comment] 2017-05-02 11:21
please include as much info as you can including general system you use (Since all windowers systems seems to be functioning differently atm, and include if you have the windowers 10 creators edition and if your using a XiLoader)
-Conditions that lead to the problem (Was it a simple update or di it happen while you were playing,
-Your windower version/hook and if its the dev version
-plugin or addon that are currently active when the problem started (Since some people have been using older versions) 
-and any dump reports that may have arisen as a resulted

**Comment by Byrth** [comment] 2017-05-04 20:05
Binds should be fixed in hook.dll version 4.3.0.8, which is currently on -dev ( http://update.windower.net/dev/Windower.exe )

Please let us know if it worked for you.

This is a duplicate of #903, so I'm going to close it now but feel free to post in that thread.

**Closed by Byrth** 2017-05-04 20:05 UTC
