### ISSUE TITLE
CS Event fails to complete in Kamihr Drifts - "Breaking the Ice"

### ISSUE THREAD

**Issue by claywar** [Windower/Issues#1099] opened 2023-11-28 17:30 UTC
Location: Kamihr Drifts FS
NPC: Traiffeaux

Talk to Traiffeaux through the event (24), for the quest "Breaking the Ice", and progress to the point where it changes views to a different location (not pos change) than Frontier Station.

Result is black screen with no transition with Windower running, while POL-only will proceed properly in the event.  Initially reproduced on retail, but can also be tested using other means.

**Comment by RubenatorX** [comment] 2023-11-28 17:37
This is a well documented bug.
https://www.bg-wiki.com/ffxi/Breaking_the_Ice
![image](https://github.com/Windower/Issues/assets/5944121/d740bc58-f302-4265-9ac1-39dbe0dbc1b1)
But we have no idea what causes it and therefore no idea how to fix it, and Ashita presumably has the same issue (at least according to bgwiki).
_edit: I originally mistakenly said this was a 60fps bug but, this is not a framerate bug_

**Comment by RubenatorX** [comment] 2023-11-28 21:24
Also closing as this is a duplicate of #399

**Closed as completed by RubenatorX** 2023-11-28 21:24 UTC
