### ISSUE TITLE
Windower 4 will not launch Play Online Viewer after Windows 1010.0.15063.138 update

### ISSUE THREAD

**Issue by jonchan229** [Windower/Issues#876] opened 2017-04-12 05:59 UTC

**Comment by jonchan229** [comment] 2017-04-12 06:00
Windower 4 will not launch Play Online Viewer after Windows 10 10.0.15063.138 update

**Comment by z16** [comment] 2017-04-12 07:43
Duplicate of #867, which has been fixed, but due to some issues we did not push the update yet. We're trying to work them out and will then push the new Windower version.

**Closed by z16** 2017-04-12 07:43 UTC

**Comment by Alandia87** [comment] 2017-04-13 09:57
Ashita2 will good to  launch Play Online -v -

**Comment by shivaeyes** [comment] 2017-04-18 09:17
News from #753 : no more crash during the transition between pol and ff. Seems to work well ^^ thx :)
