### ISSUE TITLE
addon lua ：itemizer 

### ISSUE THREAD

**Issue by wuqinpu** [Windower/Issues#1081] opened 2021-10-13 14:09 UTC
The itemizer is still the problem, hasn't been updated yet?

**Comment by Nifim** [comment] 2021-10-13 14:23
duplicate of #1080, the that issue is closed the problem will have been fixed.
Also no need to post a new issue, you can add a comment to the existing one asking for update

**Closed as completed by Nifim** 2021-10-13 14:23 UTC

**Comment by wuqinpu** [comment] 2021-10-13 14:52
I see, I won’t be like this next time, thank you very much for your hard work
