### ISSUE TITLE
Gearswap Freezing Windower Instance

### ISSUE THREAD

**Issue by rookie6256** [Windower/Issues#725] opened 2015-05-15 21:57 UTC
I've been having an issue where when i use /ja's the game will randomly freeze up and then stop responding shortly there after.  I've done a file verification which didn't resolve the issue .  Is there something i need to edit inside the .luas im using?  Here is a dropbox link to the SMN.lua im currently using: https://www.dropbox.com/s/s0xudgva5wi674a/SMN.lua?dl=0

**Comment by z16** [comment] 2015-05-22 06:00
Is this still an issue? It may have been fixed with a few updates since the last FFXI update.

**Comment by Byrth** [comment] 2015-08-08 16:29
GearSwap appears to be working, If you still have the issue, the problem is likely a loop in the user file.

**Closed by Byrth** 2015-08-08 16:29 UTC
