### ISSUE TITLE
GearSwap lua occasionally causing pol crash.

### ISSUE THREAD

**Issue by infernoboy** [Windower/Issues#784] opened 2015-10-07 16:42 UTC
I'm using a BRD lua file that utilizes coroutines to tell me when to re-play songs on a specific target. Occasionally the game will crash and I have no idea what's causing it. It only happens when I'm on BRD so I figured it must be something to do with the GS lua. Here's the lua file I'm using: https://gist.github.com/infernoboy/6787217a79b4777a66f0

**Comment by Byrth** [comment] 2015-11-07 22:54
The last time I tried to use coroutines in GearSwap user files it just directly crashed. Your occasional crashes actually represent an improvement over the assumed condition.

The workaround that doesn't use coroutines is to use send_command('wait X;gs c ____')

**Comment by infernoboy** [comment] 2015-11-07 22:58
Yeah, I know I can do @wait, but I'd like to be able to cancel them which
isn't possible with waits. This is to avoid seeing recast messages that are
no longer required, i.e, only the latest cast on a person should show an
eventual recast message. With a wait, all messages will be shown.

On Nov 7, 2015, at 5:54 PM, Byrth <notifications@github.com> wrote:

The last time I tried to use coroutines in GearSwap user files it just
directly crashed. Your occasional crashes actually represent an improvement
over the assumed condition.

The workaround that doesn't use coroutines is to use send_command('wait
X;gs c ____')

—
Reply to this email directly or view it on GitHub
<https://github.com/Windower/Issues/issues/784#issuecomment-154761188>.

**Comment by Byrth** [comment] 2015-11-07 23:01
Well, up to Arcon then. It's a problem with the LuaCore implementation of coroutines, so there's nothing I can do on the GearSwap side.

IIRC this was a fairly complicated problem (something something coroutines always return to the global environment something), which is why it wasn't fixed. Now that someone else has found it though, perhaps it will be fixed!

**Comment by z16** [comment] 2015-11-08 06:03
Honestly, I'm not sure I'll be able to fix it at all. The problem is, as mentioned, regarding the different environment GS uses for its user scripts. This doesn't mesh well with our implementation, which doesn't consider environments at all. But this is just about everything I know about the issue. Maybe @alphaONE2  knows more? Either way, I don't even know where to start to fix this issue, so I wouldn't expect it to happen anytime soon, especially since I don't really have the time to dedicate to it at this point. I wasn't able to get any Windower related coding done in the last three weeks, and I still have a back log of other things to do :\ So I wouldn't hold my breath if I were you.

For the record, there is a pretty shitty but workable way to cancel them with waits. Use `send_command('wait x; some_alias')`. The important part here is to use `some_alias` to the command instead of the actual command. To "cancel" it just remove the alias. Then, after `x` seconds have passed, it will try to execute the alias, but will not fail it and the command will fail. I know it's pretty shitty, but it works, it's not very hard to do and it's somewhat reliable.

Another way to achieve it would be to make a different addon, a BRD helper addon. Inside that addon you could check either text or packets for an action and react to that, similar as GS does. This would be the cleaner solution by far, unless the command you want to execute is tied to GS in some way.

**Comment by alphaONE2** [comment] 2015-11-08 16:47
I don't actually think the problem is related to function environments at all. Our implementation doesn't access the current function environment in any way; everything is handled through the registry table, which is shared across all coroutines and function environments. I think it's more likely some sort of bad interaction with `pcal`l/`xpcall` which Gearswap makes heavy use of.

There are a number of limitations regarding coroutines and pcall that are part of Lua itself and out of our hands. For instance It's not possible to yield across a pcall in Lua. It's also not possible to yield across a C stack frame. If there's a Lua &rarr; `pcall` &rarr; Lua or Lua &rarr; C &rarr; Lua stack transition anywhere on the stack and a function attempts to yield, bad things will happen.

Both cases should result in a call to `error()`, and if we have any unprotected paths in LuaCore, that will result in Lua calling its panic function, which ultimately calls `std::abort()` terminating the process. The problem is it's very difficult to track down where such an unprotected path may be hiding.

**Comment by alphaONE2** [comment] 2015-11-08 17:10
As a side note, Gearswap could actually fix the `pcall` issue itself, by implementing something similar to what we do in LuaCore. If a user function `f` is always called by using `coroutine.create(f)` to construct a coroutine `c` and then using `coroutine.resume(c)` instead of `pcall(f)`, then if `coroutine.status(c) == 'suspended'` ask LuaCore to reschedule the coroutine on its behalf.

The one gotcha would be handling calls to `coroutine.sleep`. We currently implement this function as a call to `coroutine.yield` where the first argument is a sentinel userdatum which holds the delay. LuaCore can detect and read from this sentinel to differentiate between a yield and a sleep. Gearswap could detect the sentinel, but wouldn't be able to extract the delay from it for the call to `coroutine.schedule`. To work around this Gearswap would need to replace `coroutine.sleep` in the user environment and do something similar with a sentinel table.

**Comment by Byrth** [comment] 2015-11-09 16:06
Because that's an incomplete solution, I think I'll just avoid it and hide the coroutine table in the user environment. Coroutines will be disabled whenever the next GearSwap update is, so I'm going to close the thread!

**Closed by Byrth** 2015-11-09 16:06 UTC
Labels: Plugin: LuaCore, Type: Bug

**Comment by infernoboy** [comment] 2015-11-09 19:35
Okay, I found a way to do all of this within gearswap without using coroutines by utilizing the "unhandled command" event. Thanks for looking into this.
