### ISSUE TITLE
PlayOnline won't start from Windower 4 after Windows 10 Fall Creator Update applied.

### ISSUE THREAD

**Issue by IBHalliwell** [Windower/Issues#953] opened 2017-10-22 01:08 UTC
Hello,

Windower 4 starts fine.  When I click on default profile (or any profile), Windower says it is launching PlayOnline but PlayOnline never starts.

There are no error messages nor abnormal termination of Windower 4.  It goes away as though PlayOnline started.

I can manually start PlayOnline, but then I don't get the Windower 4 features.

Thank you.

**Comment by cairface** [comment] 2017-10-22 01:24
Duplicate of #942.

**Closed by cairface** 2017-10-22 01:24 UTC

**Comment by VelesX-III** [comment] 2017-10-25 06:31
#942 Is still not resolved. Consequently neither is this one, I'm afraid. My apologies for this being such a particularly aggravating issue.
