### ISSUE TITLE
Black Screen on CS in Ro'maeve for Shantoto Ascencion

### ISSUE THREAD

**Issue by kaincenteno** [Windower/Issues#1051] opened 2019-12-10 04:18 UTC
CS 71 in Ro'Maeve leads to black screen after opening door.

This issue only happens on windower, if running using xiloader from command prompt this issue doesn't happen.

**Comment by RubenatorX** [comment] 2019-12-10 04:58
For clarity, this is mission 8, and it is documented on bgwiki
 https://www.bg-wiki.com/bg/A_Shantotto_Ascension_Mission_8

**Comment by Nifim** [comment] 2024-11-25 05:33
Also closing as this is a duplicate of https://github.com/Windower/Issues/issues/399

**Closed as completed by Nifim** 2024-11-25 05:33 UTC
