### ISSUE TITLE
Shortcut key not working

### ISSUE THREAD

**Issue by lewyo** [Windower/Issues#896] opened 2017-05-01 14:44 UTC
Since the launcher and hook update that i downloaded on Friday 28th of April 1 of my shortcut keys has stopped working and it's the shortcut key that i use the most.
 
The key combo that has stopped working is the right ALT key + J to open up my job abilities, It seems to only have affected this combo because ALT + E and ALT + H both work fine from the right ALT key, The right ALT key also brings up macros when held down and the J key works fine too so i can rule out any keyboard issue and i had no problem before Fridays update. The left ATL key works just like it should and i have no problems with this.
 
Does anyone have any ideas on what is causing this key combo to have stop working like it has always done?
 
Any help would be appreciated.
 
 
My O/S is win 7 x64 pro

**Comment by Byrth** [comment] 2017-05-04 20:05
Binds should be fixed in hook.dll version 4.3.0.8, which is currently on -dev ( http://update.windower.net/dev/Windower.exe )

Please let us know if it worked for you.

This is a duplicate of #903, so I'm going to close it now but feel free to post in that thread.

**Closed by Byrth** 2017-05-04 20:05 UTC
