### ISSUE TITLE
Turning into chocobo randomly

### ISSUE THREAD

**Issue by mrjdj1998** [Windower/Issues#773] opened 2015-09-19 01:15 UTC
I don't know if this is a game glitch or windower glitch but since the update I randomly turn into a chocobo. I've had this happen in my mog garden and in new zones during battle. Others say I look normal and it seems I am still playing normally. I can cast spells and ws all normal. It just happens randomly and it's getting annoying. The only way to fix it is log out and back in. BUT it eventually happens again. Since other people see my character normally I'm thinking this is a windower problem.

**Comment by z16** [comment] 2015-09-19 01:18
It's a *BlinkMeNot* issue related to the latest update. I will try to fix it today.

**Comment by Byrth** [comment] 2015-09-24 16:48
This should be fixed now regardless whether it was caused by BMN or DressUp. Please open a new issue or reopen this issue if the problem persists.

**Closed by Byrth** 2015-09-24 16:48 UTC
Labels: Plugin: BlinkMeNot, Type: Bug
