### ISSUE TITLE
Windower crashing before playonline login screen

### ISSUE THREAD

**Issue by simonkeenlyside** [Windower/Issues#950] opened 2017-10-05 22:48 UTC
Crash text is:

[ 4.3.6349.32679 ] 2017-10-05 22:32:55.2199230 UTC
---------------------------------------------------------------------
System.TimeoutException: The operation has timed out.
   at Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
[ 4.3.6349.32679 ] 2017-10-05 22:41:46.8449230 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

**Comment by z16** [comment] 2017-10-21 09:47
Duplicate of #942.

**Closed by z16** 2017-10-21 09:47 UTC
