### ISSUE TITLE
Windower blank display

### ISSUE THREAD

**Issue by Irrellius** [Windower/Issues#872] opened 2017-03-07 20:06 UTC
Windower loads as a plain white box. I have attempted previous fixes, reinstalling windower, reinstalling FFXI, reinstalling drivers, reinstalling Windows 10, and it's still just a plain white box, but I can't see the settings to change FFXI to a size that will display on my monitor. 

Can someone post screenshots of the different menus so I can navigate and select settings without seeing them?

**Comment by alphaONE2** [comment] 2017-03-08 03:11
Closing as duplicate of #176.

You can find a workaround on our [forums](http://forums.windower.net/index.php?/topic/588-white-screen-at-windower-launch/).

**Closed** 2017-03-08 03:12 UTC
