### ISSUE TITLE
Scoreboard - Won't Stay Invisible

### ISSUE THREAD

**Issue by FFXI-Misora** [Windower/Issues#677] opened 2015-01-27 09:11 UTC
I set visible to false under both global and character settings, but every time it loads, it sets the character visible back to true.
Deleting the individual character settings also results in it just being recreated with visible set to true next time it loads.

**Comment by z16** [comment] 2015-01-27 10:26
I assume it either sets the visibility to true explicitly then saves the settings again on load.

**Comment by Byrth** [comment] 2015-01-27 10:27
This was a design decision made by Suji, which I believe was intentional to prevent people from reporting that scoreboard never shows up. I think this was probably the right decision, as that would totally happen all the time and some folks would never be able to find scoreboard.

**Comment by FFXI-Misora** [comment] 2015-01-27 10:50
While it makes sense to have it default to visible when first installed or if the settings file is missing, but when someone actually goes and edits the settings to hide it, it should be assumed that they know what they're doing...

As it is now, I keep it off for autoload and manually load it only when going into a battle that needs parsing because having it pop up everytime I login or switch characters is just distracting.

**Comment by jerryhebert** [comment] 2015-01-27 17:13
This isn't intentional, actually. It used to work as expected but broke at some point since I've been awal, probably due to library changes. @FFXI-Misora, you should fix it! Byrth's point is interesting but it is annoying to have to hide it every time you log in, if you only one to see it now and then.

**Comment by FFXI-Misora** [comment] 2015-01-28 00:48
I did look at the code but it's too complex for me.
I tried changing "default_settings.visible" to false in the scoreboard.lua but that didn't work.

I guess making my own gearswap files is my limit lol :(

**Comment by Byrth** [comment] 2015-01-28 17:17
I'll take a look at it later and see if I can fix it to the intended behavior.

**Comment by Byrth** [comment] 2015-01-29 02:02
This is the problematic line:
```display:visibility(windower.ffxi.get_info().logged_in)```

It automatically sets scoreboard to be visible if you're logged in. I am changing it to this:
```display:visibility(display.visible and windower.ffxi.get_info().logged_in)```

**Comment by jerryhebert** [comment] 2015-01-29 02:16
Thanks Byrth. It looks like Arcon was trying to fix something and changed it to that back in May of last year, although it used to initialize based on settings. I don't know what the deal was though.

Also, I just noticed all the nice stuff you did last month too! Don't say "sorry", though-- I hated that chunk of code that you refactored. :)

**Comment by Byrth** [comment] 2015-01-29 03:45
No problem! I expanded the actions library quite a bit, but I can't think of a good way to make a command-line approach to more complicated parsing viable.

Anyway though, problem has been addressed and I'm going to close this.

**Closed by Byrth** 2015-01-29 03:45 UTC

**Comment by FFXI-Misora** [comment] 2015-01-29 06:13
Thanks Byrth!
