### ISSUE TITLE
Gearswap - Preventing /item commands via windower.send_command() and other oddities

### ISSUE THREAD

**Issue by ibm2431** [Windower/Issues#819] opened 2016-04-02 05:10 UTC
Okay, so this is a strange one.

I seem to be unable to consistently use items via windower.send_command(/item 'name' <me>) while Gearswap is loaded. First noticed this when a simple Silt/Bead Pouch popper I wrote stopped working. It did work with Gearswap loaded back when I originally wrote it, but no longer does for some reason. Unfortunately, I don't use my "popper" often enough to be able to definitively say when this became an issue.

Anyway, after some testing (including running an empty Gearswap file, so it's not my Gearswap file), I tried a simple Test.lua which only consists of:

`windower.send_command("@wait 1; input /item \"Echo Drops\" <me>");`

It'll work the _first_ time, but when I reload it to try to get it to use Drops again, nothing happens. If I completely unload Gearswap it will start working. However, if I load up Gearswap again, it stops working again. I can say that various other types of commands (/ma, /ws) still work via windower.send_command(). But it seems item is not for some reason.

Okay, so further testing:
With Gearswap loaded, attempting to use Echo Drops, but failing to (ie: while running), will allow multiple usage attempts. However, once the item is successfully used once, no further attempts are made via reloading Test.lua.

Once this nonfunctional state is reached, //lua reload gearswap is not sufficient to get the test file working again (for the first usage). It must be a full //lua unload gearswap.

More testing:
With Gearswap loaded, using Echo Drops the first time so the test file no longer works, but changing zones (Warp Ring), will allow the test file to work one more time in the new zone before going back to non-functional.

However, completely unloading Gearswap, using the test file to pop some Echo Drops, then loading Gearswap (without changing zones), the Drops won't work even the "first" time (during which GS is loaded).

**Comment by Byrth** [comment] 2016-04-02 14:49
There are two item usage packets and I've never managed to figure out exactly which one is sent when. GearSwap picks the wrong one for some items, and that's why they don't work with GearSwap loaded.

**Comment by Byrth** [comment] 2016-04-02 14:50
Because this is a duplicate of another open issue (https://github.com/Byrth/Lua-Byrth/issues/352), I'm going to close it.

**Closed by Byrth** 2016-04-02 14:50 UTC
