### ISSUE TITLE
Game Crush every 2h after login ib

### ISSUE THREAD

**Issue by Centhwevir** [Windower/Issues#855] opened 2016-11-09 23:47 UTC
Since a week or more my game crushed exactly 2h´s after login in on my char.

**Comment by Byrth** [comment] 2017-04-11 13:21
Is this still an issue? Did you find the cause?

If not, could we have some more information?
* Operating System
* Are you on -live or -dev?
* If you use ```//lua m```, an hour in do you see any negative numbers?
* If you use Task Manager to look at the amount of memory Windower is claiming, does it go upwards?
* If you unload all plugins and addons (```//unloadall;lua unloadall```), can you leave yourself logged in overnight?

Thanks~!

**Comment by 6969696969696969** [comment] 2017-04-14 21:35
I have experienced this twice with the new 4.3 build....FFXI just crashed for no reason while I was idling.  Once @ #9 in Reisenjima and the other time in Whitegate.  I don't know if this is a real issue, or just 2 random instances of it happening.

**Comment by Centhwevir** [comment] 2017-04-17 21:07
i had a Laptop with Vista as System and i didnt used lua.
Now i have a new Laptop (not only because of the Problem with the dc every 2h) and the game it self working fine only Problem is i cant get windower4 to run probably because windows10 .

**Comment by Byrth** [comment] 2017-04-18 02:30
Try the -dev branch of Windower.

http://update.windower.net/dev/Windower.exe

Major changes were made to its guts and it will likely work for you now.

**Comment by Centhwevir** [comment] 2017-04-21 13:19
oh thank you so much it feals awesome to have a working windower back.

**Comment by Byrth** [comment] 2017-04-21 19:35
Nice to hear it worked for you, going to close this now!

**Closed by Byrth** 2017-04-21 19:35 UTC
